# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include includes/customize.yaml
   
frontend: 
  themes: !include_dir_merge_named themes 

#Конфиги вынесены отдельно
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
# scene: !include includes/scenes.yaml
# tts: !include includes/tts.yaml
weather: !include includes/weather.yaml


#Отдельные папки с конфигами
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/binary_sensor
script: !include_dir_merge_named includes/scripts
shell_command: !include_dir_merge_named includes/shell_commands

sonoff: 
  username: !secret username_sonoff
  password: !secret password_sonoff
  mode: local 
  
fan: 
  - platform: xiaomi_miio_airpurifier 
    name: Увлажнитель 
    host: 192.168.103.5 
    token: !secret token_xiaomi_airhumidifier 
    model: deerma.humidifier.mjjsq 

yandex_station:
  username: !secret username_yandex
  password: !secret password_yandex 
  recognition_lang: ru-RU
  devices:
    04107884c9145420064f:  # device_id вашей колонки
      host: 192.168.100.11
      name: Яндекс станция  # имя можно задать и тут

conversation:
  intents:
    media_player.yandex_station_04107884c9145420064f: [.+]  

ios:


speedtestdotnet:
  scan_interval:
    minutes: 5

yandex_smart_home:

switch:
  - platform: template
    switches:
      pc:
        friendly_name: "Компьютер"
        turn_on:
          service: script.pc_up
          data:
            entity_id: pc
        turn_off:
          service: script.pc_down_cancel
          data:
            entity_id: pc
            # icon: mdi:power-standby

utility_meter:
  energy:
    source: sensor.plug_stiralka_2
    cycle: monthly

cover:
  - platform: template
    covers:
      pc2:
        friendly_name: "Комп2"
        open_cover:
          service: script.pc_up
        close_cover:
          service: script.pc_down
        stop_cover:
          service: script.pc_down_cancel

# calendar:
#   - platform: caldav
#     username: !secret username_yandex
#     password: !secret password_yandex
#     url: https://caldav.yandex.ru/calendars/walteg74%40yandex.ru/events-7383080/
#     calendars:
    #   - 'me'
    # custom_calendars:
    #   - name: holiday
    #     calendar: me
    #     search: 'Holiday'



camera:
  - platform: local_file
    file_path: /config/www/snapshot_beward.jpeg

# miio_gateway:
#   host: 192.168.103.9
#   port: 54321

#================TEST===============

# device_tracker:
#   - platform: bluetooth_tracker
#     interval_seconds: 1