
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
   customize: !include includes/customize.yaml
   
frontend: 
  themes: !include_dir_merge_named themes 

#Конфиги вынесены отдельно
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
# script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
yeelight: !include includes/yeelight.yaml 
tts: !include includes/tts.yaml
weather: !include includes/weather.yaml


#Отдельные папки с конфигами
sensor: !include_dir_merge_list includes/sensor 
script: !include_dir_merge_named includes/scripts
shell_command: !include_dir_merge_named includes/shell_commands

hacs: 
    token: !secret HACS_github
    appdaemon: true 
    python_script: tue 
    theme: true 
    
sonoff: 
  username: !secret username_sonoff
  password: !secret password_sonoff
  mode: local 
  
fan: 
  - platform: xiaomi_miio_airpurifier 
    name: Humidifier 
    host: 192.168.103.5 
    token: !secret token_xiaomi_airhumidifier 
    model: deerma.humidifier.mjjsq 

yandex_station:
  username: !secret username_yandex
  password: !secret password_yandex 
  devices:
    04107884c9145420064f:  # device_id вашей колонки
      host: 192.168.100.11
      name: Большая колонка  # имя можно задать и тут


yandex_smart_home:

camera:
  - platform: local_file
    file_path: /config/www/snapshot_beward.jpeg

# media_player:
#   # Use the Python ADB implementation
#   - platform: androidtv
#     name: IsBox
#     host: 192.168.103.9
#     adb_server_ip: 192.168.103.3
#     adb_server_port: 5037
    
    
# miio_gateway:
#   host: 192.168.103.9
#   port: 54321

#================TEST===============

# device_tracker:
#   - platform: bluetooth_tracker
#     interval_seconds: 1